#!/bin/bash
# fix-issue.sh — Fix a single GitHub issue using Codex CLI
# Usage: bash fix-issue.sh <issue_number>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/budget.sh"
source "$SCRIPT_DIR/lib/worktree.sh"
source "$SCRIPT_DIR/lib/github.sh"
source "$SCRIPT_DIR/lib/verify.sh"

ISSUE_NUMBER="${1:?Usage: fix-issue.sh <issue_number>}"

log_info "=== Starting fix for issue #$ISSUE_NUMBER ==="

# 1. Check budget
if ! check_budget; then
  log_warn "Skipping issue #$ISSUE_NUMBER — budget exhausted"
  exit 0
fi

# 2. Fetch issue details
ISSUE_JSON=$(gh issue view "$ISSUE_NUMBER" --repo "$GH_REPO" --json title,body 2>/dev/null)
ISSUE_TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
ISSUE_BODY=$(echo "$ISSUE_JSON" | jq -r '.body')

if [ -z "$ISSUE_TITLE" ]; then
  log_error "Could not fetch issue #$ISSUE_NUMBER"
  exit 1
fi

log_info "Issue #$ISSUE_NUMBER: $ISSUE_TITLE"

# 3. Claim issue (swap labels)
claim_issue "$ISSUE_NUMBER"

# 4. Create worktree
cd "$REPO_DIR"
git fetch origin main --quiet
create_worktree "$ISSUE_NUMBER"

# 5. Build Codex prompt
PROMPT="You are fixing a bug in altimate-code, a TypeScript/Bun CLI tool for data engineering.

Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}
${ISSUE_BODY}

The codebase is at ${WORKTREE_PATH}.
Main package: packages/opencode/src/

Rules:
- Make minimal, focused changes to fix this specific issue
- All changes in packages/opencode/src/ MUST have altimate_change markers:
  // altimate_change start — description of what you changed and why
  ... your changes ...
  // altimate_change end
- Do NOT modify files in migration/, .github/workflows/, or script/autofix/
- Do NOT add new dependencies unless absolutely necessary
- Run verification after fixing:
  bun turbo typecheck
  cd packages/opencode && bun test --timeout 30000

Fix the issue, verify it works, then stop."

# 6. Run Codex
log_info "Running Codex CLI (model: $CODEX_MODEL, timeout: ${CODEX_TIMEOUT}s)"
CODEX_LOG="$LOG_DIR/codex-issue-${ISSUE_NUMBER}-$(date +%s).log"

set +e
timeout "$CODEX_TIMEOUT" codex exec \
  --full-auto \
  --model "$CODEX_MODEL" \
  --cd "$WORKTREE_PATH" \
  "$PROMPT" \
  2>&1 | tee "$CODEX_LOG"
CODEX_EXIT=$?
set -e

if [ $CODEX_EXIT -ne 0 ]; then
  if [ $CODEX_EXIT -eq 124 ]; then
    FAIL_REASON="Codex timed out after ${CODEX_TIMEOUT}s"
  else
    FAIL_REASON="Codex exited with code $CODEX_EXIT
$(tail -20 "$CODEX_LOG")"
  fi
  mark_failed "$ISSUE_NUMBER" "$FAIL_REASON"
  increment_budget "failure"
  audit_log "$ISSUE_NUMBER" "failure" "$FAIL_REASON"
  remove_worktree "$ISSUE_NUMBER"
  exit 1
fi

# 7. Check if Codex made any changes
cd "$WORKTREE_PATH"
if git diff --quiet HEAD; then
  FAIL_REASON="No changes made by Codex"
  mark_failed "$ISSUE_NUMBER" "$FAIL_REASON"
  increment_budget "failure"
  audit_log "$ISSUE_NUMBER" "failure" "$FAIL_REASON"
  remove_worktree "$ISSUE_NUMBER"
  exit 1
fi

# 8. Run verification
if ! verify_fix "$WORKTREE_PATH"; then
  mark_failed "$ISSUE_NUMBER" "$VERIFY_ERROR"
  increment_budget "failure"
  audit_log "$ISSUE_NUMBER" "failure" "$VERIFY_ERROR"
  remove_worktree "$ISSUE_NUMBER"
  exit 1
fi

# 9. Commit and push
cd "$WORKTREE_PATH"
git add -A
git commit -m "fix: ${ISSUE_TITLE} (autofix #${ISSUE_NUMBER})

Automated fix generated by Codex CLI.
Closes #${ISSUE_NUMBER}"

BRANCH="autofix/issue-${ISSUE_NUMBER}"
git push -u origin "$BRANCH"

# 10. Create PR
PR_URL=$(create_autofix_pr "$ISSUE_NUMBER" "$ISSUE_TITLE" "$BRANCH")
log_info "PR created: $PR_URL"

# 11. Comment on issue
comment_success "$ISSUE_NUMBER" "$PR_URL"

# 12. Record success
increment_budget "success"
audit_log "$ISSUE_NUMBER" "success" "PR: $PR_URL"

# 13. Cleanup
remove_worktree "$ISSUE_NUMBER"

log_info "=== Issue #$ISSUE_NUMBER fixed successfully ==="
