#!/bin/bash
# lib/github.sh — GitHub API wrappers via gh CLI

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

# Fetch open issues labeled 'autofix': fetch_autofix_issues [limit]
# Outputs JSON array to stdout
fetch_autofix_issues() {
  local limit="${1:-5}"
  api_retry gh issue list \
    --repo "$GH_REPO" \
    --label "$GH_LABEL_AUTOFIX" \
    --state open \
    --json number,title,body \
    --limit "$limit" 2>/dev/null
}

# Claim an issue (swap labels): claim_issue <issue_number>
claim_issue() {
  local issue_number="$1"
  log_info "Claiming issue #$issue_number"
  api_retry gh issue edit "$issue_number" \
    --repo "$GH_REPO" \
    --add-label "$GH_LABEL_IN_PROGRESS" \
    --remove-label "$GH_LABEL_AUTOFIX" 2>/dev/null
}

# Mark issue as failed: mark_failed <issue_number> <reason>
mark_failed() {
  local issue_number="$1"
  local reason="$2"

  log_error "Issue #$issue_number failed: $reason"

  # Add failure label, remove in-progress
  api_retry gh issue edit "$issue_number" \
    --repo "$GH_REPO" \
    --add-label "$GH_LABEL_FAILED" \
    --remove-label "$GH_LABEL_IN_PROGRESS" 2>/dev/null

  # Comment with details
  api_retry gh issue comment "$issue_number" \
    --repo "$GH_REPO" \
    --body "**Autofix failed**

\`\`\`
$reason
\`\`\`

The autofix system attempted to fix this issue but could not produce a passing solution. A human will need to investigate." 2>/dev/null
}

# Comment success on issue: comment_success <issue_number> <pr_url>
comment_success() {
  local issue_number="$1"
  local pr_url="$2"

  api_retry gh issue comment "$issue_number" \
    --repo "$GH_REPO" \
    --body "**Autofix PR created**: $pr_url

The autofix system created a fix that passes typecheck, unit tests, and marker guard. Please review the PR." 2>/dev/null

  # Remove in-progress label
  api_retry gh issue edit "$issue_number" \
    --repo "$GH_REPO" \
    --remove-label "$GH_LABEL_IN_PROGRESS" 2>/dev/null
}

# Create a PR: create_autofix_pr <issue_number> <title> <branch>
# Outputs PR URL to stdout
create_autofix_pr() {
  local issue_number="$1"
  local title="$2"
  local branch="$3"

  api_retry gh pr create \
    --repo "$GH_REPO" \
    --title "fix: $title (autofix #$issue_number)" \
    --body "$(cat <<EOF
## Autofix PR

Closes #$issue_number

This PR was automatically generated by the autofix system using Codex CLI.

### Verification
- [x] Typecheck passes
- [x] Unit tests pass
- [x] Marker guard passes

**Please review carefully before merging.**
EOF
)" \
    --base main \
    --head "$branch" \
    --label "$GH_LABEL_AUTOFIX"
}
